### ISSUE TITLE
As a user, I want to analyze a conversation so that I can learn how to improve conversations. #3

### ISSUE THREAD

**Issue by mgordon34** [mgordon34/Conversation-Analysis#9]
## Epic Details
- [x] 3a - As a user, I want to know the inputs and outputs of the algorithm
- [x] 3b - As a user, I want to know the details of the algorithm
- [x] 3c - As a user, I want to specify the sentiments I want the software to analyze, so that my analysis result is condensed to information I am interested in
- [x] 3d - As a user, I would like to know what libraries were used to implement the algorithm
